### ISSUE TITLE
Новый движ

### ISSUE THREAD

**Issue by pngcrypt** [Isseq/Brchanrus.user.js#10]
Я тут решил переделать немного движок реплейсеров.
Сделал его более универсальным, без создания кучи ненужных объектов.
Легко расширять для новых типов (например, как ты делал для постов) - достаточно просто написать новую функцию-обработчик.

Т.е. можно создать несколько разных конфигов с реплейсерами: общий (для страниц), для постов и для чего угодно.
А потом просто вызывать реплейсеры с указанием нужного конфига.

Вот тут скелет: https://github.com/pngcrypt/ImprovedBrchanRus

**Comment by Isseq** [comment]
Потом гляну, весь день сегодня за пека

**Comment by pngcrypt** [comment]
Вроде все перенес, что было.
Потестить пока негде, зато добавил перевод для страницы техработ )

**Comment by pngcrypt** [comment]
А не... jq-перевод новых постов еще забыл

**Comment by pngcrypt** [comment]
Терь вроде всё

**Comment by pngcrypt** [comment]
Протестил. Вроде работает. Может, конечно что-то еще вылезти.
Ну что, бум на нее перекатываться?

**Comment by Isseq** [comment]
Добавил ветку https://github.com/Isseq/Brchanrus.user.js/tree/ImprovedBrchanRus
Надо ещё сделать совместимость со старыми браузерами, opera 12

**Comment by pngcrypt** [comment]
Насколько старыми? И нужно ли?
Не очень хочется практиковать некрофилию

**Comment by Isseq** [comment]
Попробовал сделать поддержку старых браузеров, ну их нахер один гемор,

**Comment by pngcrypt** [comment]
Вот и я о том же )
Кстати, у тебя в новой ветке обновление с мастера прописано (в скрипте)

**Comment by Isseq** [comment]
Да, сейчас смержу ветки

**Comment by pngcrypt** [comment]
Ну вот... Только я разобрался как ветку клонировать )

**Comment by pngcrypt** [comment]
А кому надо, пусть сам пилит поддержку для некробраузера. Я так щитаю

**Comment by Isseq** [comment]
Ага, смержил ветки

**Comment by pngcrypt** [comment]
А тебе как удобнее: самому чекать мои коммиты или мне тебе пулреквесты кидать?

**Comment by Isseq** [comment]
Самому конечно, через smartgit удобнее

**Comment by pngcrypt** [comment]
Ок, просто не шарю )

**Comment by pngcrypt** [comment]
Я через с черепашкой работаю

**Comment by pngcrypt** [comment]
Какая-то хрень с console.group - она че-то для всех открытых окон применяется

**Comment by pngcrypt** [comment]
Хм... Короче, (в лисе по крайней мере) если открываешь линк из дочернего окна в новой вкладке, то там скрипт не перезапускается и консоль у этих двух окон становится общей.
Надо че-то подкрутить в гризманки наверное? Я хз

**Comment by pngcrypt** [comment]
Отбой короч )
Это сраная группировка в firebug отключается. Очень "полезная" фича, надо сказать
